#!/usr/bin/env python3
"""
Backup all fleet git repositories to Google Drive.
Creates/updates dated folder "Website & App Source Backups - YYYY-MM-DD"
under "/Users/jay/Google Drive/My Drive" (or CloudStorage path).
"""

import os
import sys
import shutil
import zipfile
import datetime
import stat

DATE_STR = datetime.date.today().strftime("%Y-%m-%d")

# 1. Locate Google Drive
GDRIVE_CANDIDATES = [
    "/Users/jay/Google Drive/My Drive",
    "/Users/jay/Library/CloudStorage/GoogleDrive-jaywedgeworth22@gmail.com/My Drive",
]

GDRIVE_ROOT = None
for cand in GDRIVE_CANDIDATES:
    if os.path.isdir(cand):
        GDRIVE_ROOT = cand
        break

if not GDRIVE_ROOT:
    print("❌ Error: Google Drive directory not found on this machine.", file=sys.stderr)
    sys.exit(1)

DEST_DIR = os.path.join(GDRIVE_ROOT, f"Website & App Source Backups - {DATE_STR}")
os.makedirs(DEST_DIR, exist_ok=True)
print(f"📂 Target Google Drive folder: {DEST_DIR}")

CODE_ROOT = "/Users/jay/Code"
REPOS = [
    "Socratic.Trade",
    "Congress.Trade",
    "Usage-Monitor",
    "congress-trading-shared",
    "DealDex",
    "Personal-Site",
    "ai-fleet-coordinator",
    "TopSpin",
    "ContactLogo",
]

EXCLUDE_DIRS = {
    "node_modules", ".next", ".turbo", "dist", "build",
    ".dart_tool", "Pods", ".git", ".cache", ".venv", "venv",
    ".gradle", ".idea", ".DS_Store"
}

EXCLUDE_EXTS = {
    ".sock", ".log", ".tmp", ".swp", ".pyc"
}

DOC_FILES = ["README.md", "AGENTS.md", "STATUS.md", "PLAN.md", "PROJECT.md", "package.json", "Cargo.toml", "pubspec.yaml"]

for repo in REPOS:
    repo_path = os.path.join(CODE_ROOT, repo)
    if not os.path.isdir(repo_path):
        print(f"⚠️ Skipping {repo} (not found at {repo_path})")
        continue

    print(f"📦 Backing up {repo}...")
    zip_out = os.path.join(DEST_DIR, f"{repo}-backup-{DATE_STR}.zip")

    file_count = 0
    with zipfile.ZipFile(zip_out, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(repo_path):
            # Prune excluded directories in-place
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith(".")]

            for file in files:
                ext = os.path.splitext(file)[1].lower()
                if ext in EXCLUDE_EXTS or file == ".DS_Store":
                    continue

                full_path = os.path.join(root, file)
                try:
                    st = os.lstat(full_path)
                    # Skip sockets, FIFO, symlinks to missing files, etc.
                    if stat.S_ISSOCK(st.st_mode) or stat.S_ISFIFO(st.st_mode):
                        continue
                    if os.path.islink(full_path) and not os.path.exists(full_path):
                        continue

                    rel_path = os.path.relpath(full_path, repo_path)
                    zf.write(full_path, arcname=os.path.join(repo, rel_path))
                    file_count += 1
                except Exception as e:
                    # Skip problematic unreadable files safely
                    pass

    size_mb = os.path.getsize(zip_out) / (1024 * 1024)
    print(f"  ✓ Saved {repo}-backup-{DATE_STR}.zip ({file_count} files, {size_mb:.2f} MB)")

    # Copy top-level doc files
    doc_dest = os.path.join(DEST_DIR, f"{repo} (source docs)")
    os.makedirs(doc_dest, exist_ok=True)
    for doc in DOC_FILES:
        doc_src = os.path.join(repo_path, doc)
        if os.path.isfile(doc_src):
            try:
                shutil.copy2(doc_src, os.path.join(doc_dest, doc))
            except Exception:
                pass

# Write BACKUP-NOTES.md
notes_path = os.path.join(DEST_DIR, "BACKUP-NOTES.md")
with open(notes_path, "w") as f:
    f.write(f"""# Source Backups — {DATE_STR}

Comprehensive backup of all active AI fleet repositories from `/Users/jay/Code`.

## Included Repositories
- **Socratic.Trade** — full source (excluding node_modules/build artifacts)
- **Congress.Trade** — full source
- **Usage-Monitor** — full source
- **congress-trading-shared** — full source
- **DealDex** — full source
- **Personal-Site** — portfolio and static mirror source
- **ai-fleet-coordinator** — fleet protocols, scripts, and skills
- **TopSpin** — source
- **ContactLogo** — source

## Backup Structure
- Zip archives (`*-backup-{DATE_STR}.zip`): Clean source trees for offline recovery.
- Source docs folders (`* (source docs)`): Key documentation (`README.md`, `AGENTS.md`, etc.) for direct online browsing in Google Drive.

Generated by: `scripts/backup-fleet-to-gdrive.py`
""")

print(f"\n✅ All repositories backed up successfully to:\n   {DEST_DIR}")
