#!/usr/bin/env bash
# Backup all fleet git repositories to Google Drive
# Creates/updates dated folder "Website & App Source Backups - YYYY-MM-DD"
# under "/Users/jay/Google Drive/My Drive" (or CloudStorage path).

set -euo pipefail

DATE_STR="$(date +%Y-%m-%d)"
GDRIVE_ROOT=""

if [[ -d "/Users/jay/Google Drive/My Drive" ]]; then
  GDRIVE_ROOT="/Users/jay/Google Drive/My Drive"
elif [[ -d "/Users/jay/Library/CloudStorage/GoogleDrive-jaywedgeworth22@gmail.com/My Drive" ]]; then
  GDRIVE_ROOT="/Users/jay/Library/CloudStorage/GoogleDrive-jaywedgeworth22@gmail.com/My Drive"
fi

if [[ -z "$GDRIVE_ROOT" ]]; then
  echo "❌ Error: Google Drive folder not found on this machine." >&2
  exit 1
fi

DEST_DIR="${GDRIVE_ROOT}/Website & App Source Backups - ${DATE_STR}"
mkdir -p "$DEST_DIR"

echo "📂 Target Google Drive folder: $DEST_DIR"

REPOS=(
  "Socratic.Trade"
  "Congress.Trade"
  "Usage-Monitor"
  "congress-trading-shared"
  "DealDex"
  "Personal-Site"
  "ai-fleet-coordinator"
  "TopSpin"
  "ContactLogo"
)

CODE_ROOT="/Users/jay/Code"

for repo in "${REPOS[@]}"; do
  src="${CODE_ROOT}/${repo}"
  if [[ ! -d "$src" ]]; then
    echo "⚠️ Warning: Directory $src not found, skipping."
    continue
  fi

  echo "📦 Backing up $repo..."
  zip_out="${DEST_DIR}/${repo}-backup-${DATE_STR}.zip"
  
  # Create a clean zip excluding node_modules, .next, dist, build, .turbo, etc.
  (
    cd "$src"
    zip -rq "$zip_out" . \
      -x "*/node_modules/*" \
      -x "*/.next/*" \
      -x "*/.turbo/*" \
      -x "*/dist/*" \
      -x "*/build/*" \
      -x "*/.dart_tool/*" \
      -x "*/Pods/*" \
      -x "*/.git/*" \
      -x "*.log" \
      -x "*.tmp"
  )
  
  # Also copy top-level docs/metadata folder for quick viewing without unzipping
  doc_dest="${DEST_DIR}/${repo} (source docs)"
  mkdir -p "$doc_dest"
  for doc_file in README.md AGENTS.md STATUS.md PLAN.md PROJECT.md package.json; do
    if [[ -f "${src}/${doc_file}" ]]; then
      cp "${src}/${doc_file}" "$doc_dest/"
    fi
  done
  
  echo "  ✓ Saved ${repo}-backup-${DATE_STR}.zip ($(du -h "$zip_out" | cut -f1))"
done

# Write BACKUP-NOTES.md in the folder
cat << NOTES_EOF > "${DEST_DIR}/BACKUP-NOTES.md"
# Source Backups — ${DATE_STR}

Comprehensive backup of all active AI fleet repositories from \`/Users/jay/Code\`.

## Included Repositories
- **Socratic.Trade** — full source (excluding node_modules/build artifacts)
- **Congress.Trade** — full source
- **Usage-Monitor** — full source
- **congress-trading-shared** — full source
- **DealDex** — full source
- **Personal-Site** — portfolio and static mirror source
- **ai-fleet-coordinator** — fleet protocols, scripts, and skills
- **TopSpin** — source
- **ContactLogo** — source

## Backup Structure
- Zip archives (\`*-backup-${DATE_STR}.zip\`): Clean source trees for offline recovery.
- Source docs folders (\`* (source docs)\`): Key documentation (\`README.md\`, \`AGENTS.md\`, etc.) for direct online browsing in Google Drive.

Generated by: \`scripts/backup-fleet-to-gdrive.sh\` on $(hostname)
NOTES_EOF

echo "✅ Backup complete! All repositories backed up to:"
echo "   $DEST_DIR"
